version: '3'
services:
  redis:
    restart: always
    image: redis
    container_name: vpt-redis
    volumes:
      - ./redis:/data
    ports:
      - 127.0.0.1:6379:6379
  web:
    restart: always
    image: voxpupuli/vox-pupuli-tasks
    container_name: vpt-web
    depends_on:
      - redis
      - postgres
    command: /vpt/entrypoint.sh
    volumes:
      - ./db/production.sqlite3:/vpt/db/production.sqlite3
      - ./log:/vpt/log
      - ./config/master.key:/vpt/config/master.key
      - ./config/database.yml:/vpt/config/database.yml
    ports:
      - 127.0.0.1:3000:3000
    environment:
      RAILS_ENV: production
      NODE_ENV: production
      RAILS_SERVE_STATIC_FILES: y
  sidekiq:
    restart: always
    image: voxpupuli/vox-pupuli-tasks
    container_name: vpt-sidekiq
    depends_on:
      - redis
      - postgres
    volumes:
      - ./db/production.sqlite3:/vpt/db/production.sqlite3
      - ./log-sidekiq:/vpt/log
      - ./config/master.key:/vpt/config/master.key
      - ./config/database.yml:/vpt/config/database.yml
    command: bundle exec sidekiq
    environment:
      RAILS_ENV: production
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60
  postgres:
    image: postgres:12.1
    environment:
      POSTGRES_PASSWORD: vptpgpassword
      POSTGRES_USER: vpt
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
  jaeger:
    image: jaegertracing/all-in-one:1.22
    container_name: jaeger
    ports:
      - "5775:5775/udp"
      - "5778:5778"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "9411:9411"
      - "14268:14268"
      - "14250:14250"
      - "16686:16686"
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: ":9411"
